<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-content nopadding">
				<div class="control-group">
					<div style="margin-left:40px">
						<h4>Agregar fotos</h4>
						<form id="fileupload" method="post" enctype="multipart/form-data"> 
							<noscript><input type="hidden" name="redirect" value="http://blueimp.github.com/jQuery-File-Upload/"></noscript>
							<div class="row-fluid fileupload-buttonbar">
								<div class="span7">
									<span class="btn btn-success fileinput-button">
										<i class="icon-plus icon-white"></i>
										<span>Agregar fotos</span>
										<input type="file" name="files[]" multiple>
									</span>
									<button type="submit" class="btn btn-primary start">
										<i class="icon-upload icon-white"></i>
										<span>Comenzar</span>
									</button>
									<button type="reset" class="btn btn-warning cancel">
										<i class="icon-ban-circle icon-white"></i>
										<span>Cancelar</span>
									</button>
									<button type="button" class="btn btn-danger delete">
										<i class="icon-trash icon-white"></i>
										<span>Borrar</span>
									</button>
									<input type="checkbox" class="toggle"> 
									<span class="fileupload-loading"></span>
								</div>
								<div class="span5 fileupload-progress fade">
									<div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
									<div class="bar" style="width:0%;"></div>
								</div>	 
								<div class="progress-extended">&nbsp;</div>
							</div>
						</div>
						<table role="presentation" class="table table-striped">
							<tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
						</table>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
        <tr class="template-upload fade">
            <td>
                <span class="preview"></span>
            </td>
            <td>
                <p class="name">{%=file.name%}</p>
                {% if (file.error) { %}
                    <div><span class="label label-important">Error</span> {%=file.error%}</div>
                {% } %}
            </td>
            <td>
                <p class="size">{%=o.formatFileSize(file.size)%}</p>
                {% if (!o.files.error) { %}
                    <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                    	<div class="bar" style="width:0%;"></div>
                    </div>
                {% } %}
            </td>
            <td>
                {% if (!o.files.error && !i && !o.options.autoUpload) { %}
                    <button class="btn btn-primary start">
                        <i class="icon-upload icon-white"></i>
                        <span>Comenzar</span>
                    </button>
                {% } %}
                {% if (!i) { %}
                    <button class="btn btn-warning cancel">
                        <i class="icon-ban-circle icon-white"></i>
                        <span>Cancelar</span>
                    </button>
                {% } %}
            </td>
        </tr>
    {% } %}
</script>
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
        <tr class="template-download fade">
    	    <td>
                <span class="preview">
                    {% if (file.thumbnailUrl) { %}
                        <a href="{%=file.url%}" title="{%=file.name%}" data-gallery="gallery" download="{%=file.name%}">
                            <img src="{%=file.thumbnailUrl%}">
                        </a>
                    {% } %}
                </span>
            </td>
            <td>
                <p class="name">
                    <a href="{%=file.url%}" title="{%=file.name%}" data-gallery="{%=file.thumbnailUrl&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
                </p>
                {% if (file.error) { %}
                    <div><span class="label label-important">Error</span> {%=file.error%}</div>
                {% } %}
            </td>
    		<td>
       			<span class="size">{%=o.formatFileSize(file.size)%}</span>
    		</td>
    		<td>
       			<button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.delete_with_credentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
           			<i class="icon-trash icon-white"></i>
                    <span>Borrar</span>
       			</button>
       			<input type="checkbox" name="delete" value="1" class="toggle">
    		</td>
    	</tr>
    {% } %}
</script>