<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Error 404</title>
</head>
<body>
  <h1>Error 404</h1>
  <h2><?php //echo $this->message ?>Página no encontrada</h2>

  <?php /*

  <?php if (isset($this->exception)): ?>
  
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php endif ?>

  */ ?>
  <br>
  <br>
  <h5>Volver a <a href="<?php echo URL ?>/funcionarios/">Funcionarios</a></h5>

</body>
</html>
