<div class="row-fluid">
	<div class="span12">
		<div class="widget-box">
			<div class="widget-title">
				<span class="icon">
					<i class="icon-align-justify"></i>									
				</span>
				<h5>Crear nuevo usuario</h5>
			</div>
			<div class="widget-content nopadding">
				<?php if(isset($this->msj)) { ?>
					<div class="alert alert-success">
						<button class="close" data-dismiss="alert">×</button>
						<strong>Éxito</strong> <?php echo $this->msj ?>
					</div>
				<?php } ?>
				<form id="form-crear-usuario" method="post" class="form-horizontal" />
					<div class="control-group <?php echo(isset($this->err['nombre'])) ? 'error' : '' ?>">
						<label class="control-label">Nombre</label>
						<div class="controls">
							<input name="usuario[nombre]" type="text" placeholder="Ej. Pedro Soto" value="<?php echo(isset($this->resp['nombre'])) ? $this->resp['nombre'] : '' ?>" />
							<div class="msj-error">
								<?php if(isset($this->err['nombre'])) { ?>
									<ul>
										<?php foreach($this->err['nombre'] as $val) { ?>
											<li><small><?php echo $val ?></small></li>
										<?php } ?>
									</ul>
								<?php } ?>
							</div>
						</div>
					</div>

					<div class="control-group <?php echo(isset($this->err['email'])) ? 'error' : '' ?>">
						<label class="control-label">Email</label>
						<div class="controls">
							<input name="usuario[email]" type="text" placeholder="Ej: nombre@email.com" value="<?php echo(isset($this->resp['email'])) ? $this->resp['email'] : '' ?>" />
							<div class="msj-error">
								<?php if(isset($this->err['email'])) { ?>
									<ul>
										<?php foreach($this->err['email'] as $val) { ?>
											<li><small><?php echo $val ?></small></li>
										<?php } ?>
									</ul>
								<?php } ?>
							</div>
						</div>
					</div>

					<div class="control-group <?php echo(isset($this->err['nombre_usuario'])) ? 'error' : '' ?>">
						<label class="control-label">Nombre de usuario</label>
						<div class="controls">
							<input name="usuario[nombre_usuario]" type="text" placeholder="Ej: nombre_algo" value="<?php echo(isset($this->resp['nombre_usuario'])) ? $this->resp['nombre_usuario'] : '' ?>" />
							<div class="msj-error">
								<?php if(isset($this->err['nombre_usuario'])) { ?>
									<ul>
										<?php foreach($this->err['nombre_usuario'] as $val) { ?>
											<li><small><?php echo $val ?></small></li>
										<?php } ?>
									</ul>
								<?php } ?>
							</div>
						</div>
					</div>

					<div class="control-group <?php echo(isset($this->err['contrasena'])) ? 'error' : '' ?>">
						<label class="control-label">Contraseña</label>
						<div class="controls">
							<input name="usuario[contrasena]" type="password" value="<?php echo(isset($this->resp['contrasena'])) ? $this->resp['contrasena'] : '' ?>" />
							<div class="msj-error">
								<?php if(isset($this->err['contrasena'])) { ?>
									<ul>
										<?php foreach($this->err['contrasena'] as $val) { ?>
											<li><small><?php echo $val ?></small></li>
										<?php } ?>
									</ul>
								<?php } ?>
							</div>
						</div>
					</div>

					<div class="control-group <?php echo(isset($this->err['recontrasena'])) ? 'error' : '' ?>">
						<label class="control-label">Repetir contraseña</label>
						<div class="controls">
							<input name="usuario[recontrasena]" type="password" value="<?php echo(isset($this->resp['recontrasena'])) ? $this->resp['recontrasena'] : '' ?>" />
							<div class="msj-error">
								<?php if(isset($this->err['recontrasena'])) { ?>
									<ul>
										<?php foreach($this->err['recontrasena'] as $val) { ?>
											<li><small><?php echo $val ?></small></li>
										<?php } ?>
									</ul>
								<?php } ?>
							</div>
						</div>
					</div>

					<div class="estado control-group <?php echo(isset($this->err['estado'])) ? 'error' : '' ?>">
						<label class="control-label">Estado</label>
						<div class="controls">
							<select id="estado" name="usuario[estado]">
								<option value="1" selected>Habilitado</option>
								<option value="0">Deshabilitado</option>
							</select>
							<div class="estado-msj"></div>
							<div class="msj-error">
								<?php if(isset($this->err['estado'])) { ?>
									<ul>
										<?php foreach($this->err['estado'] as $val) { ?>
											<li><small><?php echo $val ?></small></li>
										<?php } ?>
									</ul>
								<?php } else { ?>
									<ul></ul>
								<?php } ?>
							</div>
						</div>
					</div>

					<div class="control-group <?php echo(isset($this->err['tipo'])) ? 'error' : '' ?>">
						<label class="control-label">Tipo</label>
						<div class="controls">
							<div class="control-group">
								<select class="sel2" name="usuario[tipo]">
									<option value="0">Seleccione un tipo</option>
									<option value="ADM">Administrador</option>
									<option value="USU">Usuario</option>
								</select>
								<div class="msj-error">
									<?php if(isset($this->err['tipo'])) { ?>
										<ul>
											<?php foreach($this->err['tipo'] as $val) { ?>
												<li><small><?php echo $val ?></small></li>
											<?php } ?>
										</ul>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
					<div class="form-actions">
						<button type="submit" class="btn btn-primary">Guardar</button>
					</div>
				</form>
			</div>
		</div>						
	</div>
</div>