<div class="perfil">	
	<div id="user-profile-1" class="user-profile row-fluid">
		<div class="span3 center">
			<div>
				<span class="profile-picture">
					<img id="avatar" class="editable" alt="Alex's Avatar" src="<?php URL ?>/img/avatars/profile-pic.jpg" />
				</span>
				<div class="space-4"></div>
				<div class="width-80 label label-info label-large arrowed-in arrowed-in-right">
					<div class="inline position-relative">
						<a href="#" class="user-title-label dropdown-toggle" data-toggle="dropdown">
							<span class="white middle bigger-120"><?php echo $this->usuario->nombre ?></span>
						</a>
					</div>
				</div>
			</div>
			<div class="space-6"></div>
			<div class="hr hr12 dotted"></div>
		</div>
		<div class="span9">
			<div class="center">
				
			</div>
			<div class="space-12"></div>
			<div class="profile-user-info profile-user-info-striped">
				<div class="profile-info-row">
					<div class="profile-info-name"> Nombre </div>
					<div class="profile-info-value">
						<span class="editable" id="nombre"><?php echo $this->usuario->nombre ?></span>
					</div>
				</div>
				<div class="profile-info-row">
					<div class="profile-info-name"> Usuario </div>
					<div class="profile-info-value">
						<span class="editable" id="nombre_usuario"><?php echo $this->usuario->nombre_usuario ?></span>
					</div>
				</div>
				<div class="profile-info-row">
					<div class="profile-info-name"> Email </div>
					<div class="profile-info-value">
						<span class="editable" id="email"><?php echo $this->usuario->email ?></span>
					</div>
				</div>
				<div class="profile-info-row">
					<div class="profile-info-name"> Tipo usuario </div>
					<div class="profile-info-value">
						<span class="editable" id="tipo"><?php echo $this->usuario->tipo ?></span>
					</div>
				</div>
				<div class="profile-info-row">
					<div class="profile-info-name"> Ingresado </div>
					<div class="profile-info-value">
						<span class="editable" id="ingresado"><?php echo $this->usuario->fecha_registro ?>. (Hace <?php echo $this->usuario->fecha_desde ?>)</span>
					</div>
				</div>
			</div>
			<div class="space-20"></div>
			
			<div class="hr hr2 hr-double"></div>
			<div class="space-6"></div>
			
		</div>
	</div>
</div>