<?php if(strstr(URI, '/ingresar')) { ?>
	<p class="login-footer">
		&copy; <?php echo date('Y') ?> 
		<a target="_blank" href="http://www.davila.cl/">Clínica Dávila</a> 
		- Desarrollado por <a target="_blank" href="http://c-online.cl/">C-Online</a>
		<!--<a href="http://twitter.com/daswort">daswort</a>-->
	</p>
<?php } else { ?>
	<p>
		&copy; <?php echo date('Y') ?> 
		<a target="_blank" href="http://www.davila.cl/">Clínica Dávila</a> 
		- Desarrollado por <a target="_blank" href="http://c-online.cl/">C-Online</a>
		<!--<a href="http://twitter.com/daswort">daswort</a>-->
	</p>
<?php } ?>
