<div id="logo">
	<!--<img src="img/logo.png" alt="">-->
	<h3><?php echo NOMBRE_APP ?></h3>
</div>

<div id="loginbox">            
	<form id="loginform" class="form-vertical" method="post">	
		<p>Ingrese su usuario y contraseña para continuar.</p>
		<div class="control-group">
			<div class="controls">
				<div class="input-prepend">
					<span class="add-on"><i class="icon-user"></i></span>
					<input name="usuario[nombre_usuario]" type="text" placeholder="Usuario">
				</div>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<div class="input-prepend">
					<span class="add-on"><i class="icon-lock"></i></span>
					<input name="usuario[contrasena]" type="password" placeholder="Contraseña">
				</div>
			</div>
		</div>
		<?php if(isset($this->err)) { ?>
			<div class="alert alert-error">
				<button class="close" data-dismiss="alert">×</button>
				<strong>Error!</strong> <?php echo $this->err ?>
			</div>
		<?php } ?>

		<?php if(isset($this->msj)) { ?>
			<div class="alert alert-success">
				<button class="close" data-dismiss="alert">×</button>
				<strong>Éxito</strong> <?php echo $this->msj ?>
			</div>
		<?php } ?>
		<div class="form-actions">
			<span class="pull-right"><input type="submit" class="btn btn-inverse" value="Ingresar"></span>
		</div>
	</form>
</div>
